[package]
authors = ["Nick Platt <platt.nicholas@gmail.com>"]
name = "raft"
version = "0.1.0"

[dependencies]
docopt = "0.6.86"
docopt_macros = "0.6.86"
itertools = "0.5.5"
log = "0.3.6"
rand = "0.3.14"
rustc-serialize = "0.3.19"
slog = "1.2.0"
slog-term = "1.3.1"
